State: 6
Info: ''
Logo: PCL\Logo.png
ReleaseTime: 2023-06-12 21:25
VersionFabric: ''
VersionLegacyFabric: ''
VersionQuilt: ''
VersionLabyMod: ''
VersionOptiFine: ''
VersionLiteLoader: false
VersionForge: 47.4.10
VersionNeoForge: ''
VersionCleanroom: ''
VersionApiCode: 47040010
VersionOriginal: 1.20.1
VersionOriginalMain: 20
VersionOriginalSub: 1
VersionArgumentIndieV2: true
IsStar: true
LogoCustom: true
VersionLaunchCount: 2
